from django.db import models

class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    active_status = models.CharField(max_length=255)
    customer = models.CharField(max_length=255)
    balance = models.CharField(max_length=255)
    balance_total = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    mr = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255)
    mi = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    primary_contact = models.CharField(max_length=255)
    main_phone = models.CharField(max_length=255)
    fax = models.CharField(max_length=255)
    alt_phone = models.CharField(max_length=255)
    secondary_contact = models.CharField(max_length=255)
    job_title = models.CharField(max_length=255)
    main_email = models.CharField(max_length=255)
    bill_to_1 = models.CharField(max_length=255)
    bill_to_2 = models.CharField(max_length=255)
    bill_to_3 = models.CharField(max_length=255)
    bill_to_4 = models.CharField(max_length=255)
    bill_to_5 = models.CharField(max_length=255)
    ship_to_1 = models.CharField(max_length=255)
    ship_to_2 = models.CharField(max_length=255)
    ship_to_3 = models.CharField(max_length=255)
    ship_to_4 = models.CharField(max_length=255)
    ship_to_5 = models.CharField(max_length=255)
    customer_type = models.CharField(max_length=255)
    terms = models.CharField(max_length=255)
    rep = models.CharField(max_length=255)
    sales_tax_code = models.CharField(max_length=255)
    tax_item = models.CharField(max_length=255)
    resale_num = models.CharField(max_length=255)
    account_nro = models.CharField(max_length=255)
    credit_limit = models.CharField(max_length=255)
    job_status = models.CharField(max_length=255)
    job_type = models.CharField(max_length=255)
    job_description = models.CharField(max_length=255)
    start_date = models.CharField(max_length=255)
    projected = models.CharField(max_length=255)
    end_date = models.CharField(max_length=255)

    def __str__(self):
        return self.customer
